import { NAVIGATION } from './mobilePath';

export { NAVIGATION };

// Filtered
export const ADMIN_CTA_URLS: string[] = [
  NAVIGATION.LOAN_INTRO,
  NAVIGATION.BUSINESS_LOAN_EMPLOYMENT_TYPE,
  NAVIGATION.INVESTMENT_GOAL_SELECTION,
  NAVIGATION.INSURANCE_CLAIM,
  NAVIGATION.HOW_TO_CLAIM,
  NAVIGATION.INSURANCE_PROVIDERS,
  NAVIGATION.SIP_CALCULATOR,
  NAVIGATION.HLV_CALCULATOR,
  NAVIGATION.EMI_CALCULATOR,
  NAVIGATION.COMMUNITIES_LIST,
  NAVIGATION.GOAL_COMMUNITY,
  NAVIGATION.REFER_AND_EARN
];
