import { NAVIGATION } from './mobilePath';

export { NAVIGATION };

const EXCLUDED_PATHS = [
  NAVIGATION.LOGIN,
  NAVIGATION.HOME,
  NAVIGATION.HOME_TAB,
  NAVIGATION.SIGNUP,
  NAVIGATION.VERIFY_SIGNUP,
  NAVIGATION.VERIFY_LOGIN,
  NAVIGATION.WELCOME,
  NAVIGATION.APPLICATION_SUCCESS,
  NAVIGATION.APPLICATION_ERROR,
  NAVIGATION.INVESTMENT_SUCCESS,
];

// Filtered
export const ADMIN_CTA_URLS: string[] = Object.values(NAVIGATION).filter(
  url => !EXCLUDED_PATHS.includes(url as NAVIGATION),
);
