
export const errorCodes = {
    LEAD_NOT_FOUND: "LEAD_NOT_FOUND",
    DOB_NOT_ELIGIBLE: "DOB_NOT_ELIGIBLE",
    INVALID_ORG_TYPE: "INVALID_ORG_TYPE",
    INVALID_SALARY: "INVALID_SALARY",
    INVALID_SALARY_RANGE: "INVALID_SALARY_RANGE",
    INVALID_FOIR_PERCENTAGE: "INVALID_FOIR_PERCENTAGE",
};