import { z } from 'zod';
import { InvestmentGoalType } from './goalType';
import { UserSchema } from './auth';

export enum InvestmentGoalStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export const InvestmentGoalSchema = z.object({
  id: z.string(), // Optional because it's generated by backend during POST
  type: z.nativeEnum(InvestmentGoalType),
  name: z.string(),
  targetAmt: z.number(),
  targetDate: z.coerce.date(),
  description: z.string().optional(),
  userId: z.string(),
  user: UserSchema.optional(),
  investedAmt: z.number(),
  sipInstallment: z.number(),
  status: z.nativeEnum(InvestmentGoalStatus),
});

export const NewInvestmentGoalSchema = InvestmentGoalSchema.omit({
  id: true, // Exclude id from new goals since backend generates it
  userId: true,
  user: true,
  investedAmt: true,
  sipInstallment: true,
  status: true,
});

export const UpdateInvestmentGoalSchema = InvestmentGoalSchema.partial()
  .omit({
    type: true,
    userId: true,
    user: true,
  })
  .strict();

export type NewInvestmentGoal = z.infer<typeof NewInvestmentGoalSchema>;
export type UpdateInvestmentGoal = z.infer<typeof UpdateInvestmentGoalSchema>;
export type InvestmentGoal = z.infer<typeof InvestmentGoalSchema>;
