export enum MarketCapCategoryEnum {
  LARGE_CAP = 'LARGE_CAP',
  MID_CAP = 'MID_CAP',
  SMALL_CAP = 'SMALL_CAP',
  MICRO_CAP = 'MICRO_CAP',
  NANO_CAP = 'NANO_CAP',
  MULTI_CAP = 'MULTI_CAP',
  FLEXI_CAP = 'FLEXI_CAP',
  HYBRID = 'HYBRID',
  ELSS = 'ELSS',
  INDEX = 'INDEX',
  SECTOR = 'SECTOR',
  INTERNATIONAL = 'INTERNATIONAL',
  OTHER = 'OTHER',
  LARGE_MID_CAP = 'LARGE_MID_CAP',
}

export enum RiskProfileEnum {
  LOW = 'LOW',
  MODERATELY_LOW = 'MODERATELY_LOW',
  MODERATE = 'MODERATE',
  MODERATELY_HIGH = 'MODERATELY_HIGH',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}
